"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, CreditCard, Bitcoin, Landmark, Wallet, AlertTriangle, Gift, ShieldCheck, Copy, Search } from "lucide-react";
import { getAuthToken } from "@/lib/client-auth";
import LiveChatBot from "@/components/LiveChatBot";

const countries = ["US","CA","GB","AU","DE","FR","IT","ES","NL","BE","CH","AT","IE","PT","SE","NO","DK","FI","PL","CZ","RO","HU","GR","TR","AE","SA","QA","KW","BH","NG","GH","KE","ZA","EG","MA","IN","PK","BD","SG","MY","ID","PH","JP","KR","CN","HK","BR","MX","AR","CL","CO","NZ"];
const countryNames: Record<string,string> = { US:"United States",CA:"Canada",GB:"United Kingdom",AU:"Australia",DE:"Germany",FR:"France",IT:"Italy",ES:"Spain",NL:"Netherlands",BE:"Belgium",CH:"Switzerland",AT:"Austria",IE:"Ireland",PT:"Portugal",SE:"Sweden",NO:"Norway",DK:"Denmark",FI:"Finland",PL:"Poland",CZ:"Czech Republic",RO:"Romania",HU:"Hungary",GR:"Greece",TR:"Türkiye",AE:"United Arab Emirates",SA:"Saudi Arabia",QA:"Qatar",KW:"Kuwait",BH:"Bahrain",NG:"Nigeria",GH:"Ghana",KE:"Kenya",ZA:"South Africa",EG:"Egypt",MA:"Morocco",IN:"India",PK:"Pakistan",BD:"Bangladesh",SG:"Singapore",MY:"Malaysia",ID:"Indonesia",PH:"Philippines",JP:"Japan",KR:"South Korea",CN:"China",HK:"Hong Kong",BR:"Brazil",MX:"Mexico",AR:"Argentina",CL:"Chile",CO:"Colombia",NZ:"New Zealand" };

type Method = { id:string; key:string; name:string; type:string; minAmount:number|null; maxAmount:number|null; instructions:string|null; asset:string|null; network:string|null; walletAddress:string|null; bankName:string|null; bankAccountName:string|null; bankAccount:string|null; bankRouting:string|null; bankSwift:string|null; stripeEnabled:boolean; stripePublicKey:string|null };

export default function DepositPage() {
  const [step,setStep]=useState(1), [country,setCountry]=useState("US"), [countrySearch,setCountrySearch]=useState(""), [currency,setCurrency]=useState("USD"), [method,setMethod]=useState<Method|null>(null), [methods,setMethods]=useState<Method[]>([]), [amount,setAmount]=useState(""), [promoCode,setPromoCode]=useState(""), [promotions,setPromotions]=useState<any[]>([]), [submitted,setSubmitted]=useState(false), [error,setError]=useState(""), [loading,setLoading]=useState(true);
  const token = getAuthToken();
  const filteredCountries = useMemo(() => countries.filter(c => countryNames[c].toLowerCase().includes(countrySearch.toLowerCase()) || c.toLowerCase().includes(countrySearch.toLowerCase())), [countrySearch]);

  const load = async (selectedCountry = country) => {
    setLoading(true); setError("");
    try {
      if (selectedCountry !== country) { await fetch("/api/user/funding-profile/", { method:"PATCH", headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}, body:JSON.stringify({country:selectedCountry}) }); }
      const [m,p] = await Promise.all([fetch("/api/funding/methods/",{headers:{Authorization:`Bearer ${token}`}}),fetch("/api/user/promotions/",{headers:{Authorization:`Bearer ${token}`}})]);
      const md = await m.json(); const pd = await p.json();
      if (!m.ok) throw new Error(md.error || "Funding methods unavailable");
      setMethods(md.methods || []); setPromotions(pd.promotions || []); setMethod(prev => (md.methods || []).find((x:Method)=>x.key===prev?.key) || (md.methods || [])[0] || null);
      if (md.currency) setCurrency(md.currency);
    } catch(e:any) { setError(e.message || "Unable to load funding options"); } finally { setLoading(false); }
  };
  useEffect(()=>{ if(token) load(); else {setLoading(false);setError("Please sign in again.");} },[]);

  const selectCountry = async (c:string) => { setCountry(c); setMethod(null); setStep(1); await load(c); };
  const amountValue = Number(amount);
  const bonus = useMemo(()=>{ const p=promotions.find(x=>x.currency?.toUpperCase()===currency.toUpperCase()); if(!p || !Number.isFinite(amountValue) || amountValue<p.minDeposit) return 0; return Math.min(amountValue*(Number(p.bonusPercent||0)/100), p.maxBonus == null ? Number.POSITIVE_INFINITY : Number(p.maxBonus)); },[promotions,amountValue,currency]);
  const submit = async () => {
    setError("");
    if(!token) return setError("Please sign in again.");
    if(!method) return setError("Select a payment method.");
    if(!Number.isFinite(amountValue) || amountValue<=0) return setError("Enter a valid amount.");
    try { const res=await fetch("/api/user/transactions/",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({type:"deposit",amount:amountValue,currency,method:method.key,promoCode:promoCode.trim()||undefined})}); const data=await res.json(); if(!res.ok) throw new Error(data.error||"Deposit request failed"); setSubmitted(true); } catch(e:any){setError(e.message);} 
  };
  const copy = async (value:string) => { try { await navigator.clipboard.writeText(value); } catch {} };

  if(submitted) return <div className="min-h-screen bg-[#f7f5f1] flex items-center justify-center p-5"><div className="w-full max-w-md bg-white rounded-3xl border border-[#e5e1da] p-8 text-center shadow-sm"><Check className="mx-auto w-16 h-16 text-[#16884a] mb-5"/><h1 className="text-2xl font-black text-[#171717]">Deposit request received</h1><p className="text-sm text-[#6d6963] mt-2">Your request is recorded securely. Funds are credited only after the configured payment confirmation or authorised review.</p><Link href="/dashboard/" className="inline-flex items-center gap-2 mt-6 px-5 py-3 rounded-xl bg-[#171717] text-white text-sm font-bold">Back to Dashboard</Link></div></div>;

  return <div className="min-h-screen bg-[#f7f5f1] text-[#171717]"><header className="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-[#e5e1da]"><div className="max-w-5xl mx-auto px-4 py-4 flex items-center gap-3"><Link href="/dashboard/" className="p-2 rounded-lg hover:bg-[#f3f0eb]"><ArrowLeft size={19}/></Link><div><p className="text-[10px] uppercase tracking-[.16em] font-bold text-[#817b74]">Funds</p><h1 className="font-black">Add Funds</h1></div><div className="ml-auto flex items-center gap-2 text-xs font-bold text-[#16884a]"><ShieldCheck size={17}/> Secure funding</div></div></header>
    <main className="max-w-5xl mx-auto px-4 py-7 grid lg:grid-cols-[1fr_340px] gap-6">
      <section className="bg-white rounded-3xl border border-[#e5e1da] shadow-sm overflow-hidden"><div className="px-6 pt-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#817b74]">STEP {step} OF 4</p><h2 className="text-2xl font-black mt-1">Fund your trading account</h2></div><span className="text-xs font-bold text-[#817b74]">{countryNames[country]}</span></div><div className="mt-5 h-1.5 rounded-full bg-[#eeeae4]"><div className="h-full rounded-full bg-[#c7192d] transition-all" style={{width:`${step*25}%`}}/></div></div>
      <div className="p-6">
        {step===1&&<div><label className="text-xs font-bold uppercase tracking-wide text-[#817b74]">Country / Region</label><div className="relative mt-2"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#817b74]"/><input value={countrySearch} onChange={e=>setCountrySearch(e.target.value)} placeholder="Search country" className="w-full pl-10 pr-3 py-3 rounded-xl border border-[#dcd7d0] outline-none focus:border-[#c7192d]"/></div><div className="grid sm:grid-cols-2 gap-2 mt-3 max-h-72 overflow-y-auto">{filteredCountries.map(c=><button key={c} onClick={()=>selectCountry(c)} className={`p-3 rounded-xl border text-left ${country===c?"border-[#c7192d] bg-[#fff4f5]":"border-[#e5e1da] hover:bg-[#faf8f5]"}`}><span className="text-sm font-bold">{countryNames[c]}</span><span className="block text-[10px] text-[#817b74]">{c}</span></button>)}</div><button disabled={loading||!country} onClick={()=>setStep(2)} className="mt-5 w-full py-3.5 rounded-xl bg-[#171717] text-white font-bold disabled:opacity-50">Continue <ArrowRight size={16} className="inline ml-1"/></button></div>}
        {step===2&&<div><label className="text-xs font-bold uppercase tracking-wide text-[#817b74]">Payment method</label>{loading?<p className="py-8 text-sm text-[#817b74]">Loading available funding methods…</p>:methods.length===0?<div className="mt-3 p-5 rounded-2xl border border-amber-200 bg-amber-50 text-amber-900 text-sm"><AlertTriangle className="inline mr-2" size={17}/>No funding methods are currently enabled for this country/currency. An administrator must configure them before deposits can be accepted.</div>:<div className="grid sm:grid-cols-2 gap-3 mt-3">{methods.map(m=><button key={m.id} onClick={()=>setMethod(m)} className={`p-4 rounded-2xl border text-left transition ${method?.id===m.id?"border-[#c7192d] bg-[#fff4f5] ring-1 ring-[#c7192d]":"border-[#e5e1da] hover:border-[#bdb6ad]"}`}><div className="flex items-center gap-3">{m.type==="card"?<CreditCard/>:m.type==="crypto"?<Bitcoin/>:m.type==="bank"?<Landmark/>:<Wallet/>}<div><p className="font-bold">{m.name}</p><p className="text-[11px] text-[#817b74]">{m.type==='crypto'?`${m.asset||'Crypto'}${m.network?` · ${m.network}`:""}`:m.type==='card'?"Card payment":"Secure funding method"}</p></div></div></button>)}</div>}<div className="flex gap-2 mt-5"><button onClick={()=>setStep(1)} className="px-5 py-3 rounded-xl border border-[#dcd7d0] font-bold">Back</button><button disabled={!method} onClick={()=>setStep(3)} className="flex-1 py-3 rounded-xl bg-[#171717] text-white font-bold disabled:opacity-50">Continue</button></div></div>}
        {step===3&&<div><label className="text-xs font-bold uppercase tracking-wide text-[#817b74]">Amount</label><div className="flex mt-2 rounded-xl border border-[#dcd7d0] overflow-hidden"><input autoFocus type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="flex-1 px-4 py-4 outline-none text-lg font-bold"/><select value={currency} onChange={e=>setCurrency(e.target.value)} className="px-4 bg-[#f7f5f1] font-bold border-l border-[#dcd7d0]"><option>USD</option><option>EUR</option><option>GBP</option></select></div>{method&&(method.minAmount!==null||method.maxAmount!==null)&&<p className="text-xs text-[#817b74] mt-2">Limits: {method.minAmount??"no minimum"} – {method.maxAmount??"no maximum"} {currency}</p>}{promotions.length>0&&<div className="mt-5 p-4 rounded-2xl bg-[#fff9ed] border border-[#f0dfb5]"><div className="flex gap-2"><Gift size={17} className="text-[#c7192d]"/><div><p className="text-sm font-bold">Eligible promotion</p>{promotions.filter(p=>p.currency?.toUpperCase()===currency).slice(0,1).map(p=><p key={p.id} className="text-xs text-[#6d6963] mt-1">{p.name} · {p.bonusPercent}% bonus up to {p.maxBonus??"no cap"} {p.currency}</p>)}</div></div><input value={promoCode} onChange={e=>setPromoCode(e.target.value.toUpperCase())} placeholder="Promo code" className="w-full mt-3 px-3 py-2.5 rounded-lg border border-[#ddd5c8] bg-white text-sm"/>{bonus>0&&<p className="text-xs font-bold text-[#16884a] mt-2">Estimated qualifying bonus: {bonus.toFixed(2)} {currency}</p>}</div>}<div className="flex gap-2 mt-5"><button onClick={()=>setStep(2)} className="px-5 py-3 rounded-xl border border-[#dcd7d0] font-bold">Back</button><button disabled={!Number.isFinite(amountValue)||amountValue<=0} onClick={()=>setStep(4)} className="flex-1 py-3 rounded-xl bg-[#171717] text-white font-bold disabled:opacity-50">Review</button></div></div>}
        {step===4&&<div><p className="text-xs font-bold uppercase tracking-wide text-[#817b74]">Review & pay</p><div className="mt-3 rounded-2xl border border-[#e5e1da] divide-y divide-[#eeeae4]"><div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Country</span><b className="text-sm">{countryNames[country]}</b></div><div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Method</span><b className="text-sm">{method?.name}</b></div><div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Deposit</span><b className="text-sm">{amountValue.toFixed(2)} {currency}</b></div>{bonus>0&&<div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Estimated bonus</span><b className="text-sm text-[#16884a]">+{bonus.toFixed(2)} {currency}</b></div>}</div>{method?.type==="crypto"&&method.walletAddress&&<div className="mt-4 p-4 rounded-2xl bg-[#f7f5f1]"><p className="text-xs font-bold">Send {method.asset||"crypto"} on {method.network||"the configured network"} to</p><div className="mt-2 flex gap-2"><code className="flex-1 break-all text-xs font-bold bg-white p-3 rounded-lg border">{method.walletAddress}</code><button onClick={()=>copy(method.walletAddress!)} className="p-3 rounded-lg bg-white border" aria-label="Copy wallet address"><Copy size={16}/></button></div>{method.instructions&&<p className="text-xs text-[#6d6963] mt-2">{method.instructions}</p>}</div>}{method?.type==="bank"&&<div className="mt-4 p-4 rounded-2xl bg-[#f7f5f1] text-xs space-y-1">{method.bankName&&<p><b>Bank:</b> {method.bankName}</p>}{method.bankAccountName&&<p><b>Account name:</b> {method.bankAccountName}</p>}{method.bankAccount&&<p><b>Account:</b> {method.bankAccount}</p>}{method.bankRouting&&<p><b>Routing:</b> {method.bankRouting}</p>}{method.bankSwift&&<p><b>SWIFT:</b> {method.bankSwift}</p>}{method.instructions&&<p className="pt-2 text-[#6d6963]">{method.instructions}</p>}</div>}{method?.type==="card"&&<div className="mt-4 p-4 rounded-2xl bg-[#f7f5f1] text-sm">Your card payment will use the configured Stripe checkout. The transaction remains pending until Stripe confirms payment.</div>}{error&&<p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<div className="flex gap-2 mt-5"><button onClick={()=>setStep(3)} className="px-5 py-3 rounded-xl border border-[#dcd7d0] font-bold">Back</button><button onClick={submit} className="flex-1 py-3 rounded-xl bg-[#c7192d] text-white font-bold">Submit funding request</button></div></div>}
      </div></section>
      <aside className="space-y-4"><div className="bg-white rounded-3xl border border-[#e5e1da] p-5"><p className="text-xs font-bold uppercase tracking-wide text-[#817b74]">Funding summary</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#817b74]">Country</span><b>{countryNames[country]}</b></div><div className="flex justify-between"><span className="text-[#817b74]">Method</span><b>{method?.name||"Select method"}</b></div><div className="flex justify-between"><span className="text-[#817b74]">Amount</span><b>{Number.isFinite(amountValue)&&amountValue>0?`${amountValue.toFixed(2)} ${currency}`:"—"}</b></div></div></div><div className="p-4 rounded-2xl bg-[#171717] text-white text-xs"><ShieldCheck size={17} className="mb-2"/><p className="font-bold">Secure, server-side funding</p><p className="text-white/60 mt-1">Balances are not changed by the browser. Payment confirmation or authorised review is required.</p></div></aside>
    </main><LiveChatBot/></div>;
}
