"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, CreditCard, Bitcoin, Landmark, Wallet, AlertTriangle, Gift, ShieldCheck, Copy, Search } from "lucide-react";
import { getAuthToken } from "@/lib/client-auth";
import LiveChatBot from "@/components/LiveChatBot";

const countries: Record<string,string> = { US:"United States",CA:"Canada",GB:"United Kingdom",AU:"Australia",DE:"Germany",FR:"France",IT:"Italy",ES:"Spain",NL:"Netherlands",CH:"Switzerland",IE:"Ireland",PT:"Portugal",SE:"Sweden",NO:"Norway",DK:"Denmark",FI:"Finland",PL:"Poland",CZ:"Czech Republic",RO:"Romania",TR:"Türkiye",AE:"United Arab Emirates",SA:"Saudi Arabia",QA:"Qatar",KW:"Kuwait",BH:"Bahrain",NG:"Nigeria",GH:"Ghana",KE:"Kenya",ZA:"South Africa",EG:"Egypt",MA:"Morocco",IN:"India",PK:"Pakistan",BD:"Bangladesh",SG:"Singapore",MY:"Malaysia",ID:"Indonesia",PH:"Philippines",JP:"Japan",KR:"South Korea",CN:"China",HK:"Hong Kong",BR:"Brazil",MX:"Mexico",AR:"Argentina",CL:"Chile",CO:"Colombia",NZ:"New Zealand" };
type Method={id:string;key:string;name:string;type:string;minAmount:number|null;maxAmount:number|null;instructions:string|null;asset:string|null;network:string|null;walletAddress:string|null;bankName:string|null;bankAccountName:string|null;bankAccount:string|null;bankRouting:string|null;bankSwift:string|null;stripeEnabled:boolean;stripePublicKey:string|null};

export default function DepositPage(){
 const token=getAuthToken(); const [step,setStep]=useState(1),[country,setCountry]=useState("US"),[search,setSearch]=useState(""),[currency,setCurrency]=useState("USD"),[methods,setMethods]=useState<Method[]>([]),[method,setMethod]=useState<Method|null>(null),[amount,setAmount]=useState(""),[promoCode,setPromoCode]=useState(""),[promotions,setPromotions]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[done,setDone]=useState(false),[paying,setPaying]=useState(false);
 const load=async(c?:string)=>{setLoading(true);setError("");try{const [m,p]=await Promise.all([fetch("/api/funding/methods/",{headers:{Authorization:`Bearer ${token}`}}),fetch("/api/user/promotions/",{headers:{Authorization:`Bearer ${token}`}})]);const md=await m.json(),pd=await p.json();if(!m.ok)throw new Error(md.error||"Funding methods unavailable");if(md.country)setCountry(md.country);if(md.currency)setCurrency(md.currency);setMethods(md.methods||[]);setPromotions(pd.promotions||[]);setMethod((md.methods||[])[0]||null)}catch(e:any){setError(e.message||"Unable to load funding options")}finally{setLoading(false)}};
 useEffect(()=>{if(token)load();else{setLoading(false);setError("Please sign in again.")}},[]);
 const chooseCountry=async(c:string)=>{setCountry(c);setMethod(null);setStep(1);setSearch("");try{const r=await fetch("/api/user/funding-profile/",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({country:c})});if(!r.ok)throw new Error("Could not save country");await load(c)}catch(e:any){setError(e.message)}};
 const countryList=Object.entries(countries).filter(([code,name])=>(`${code} ${name}`).toLowerCase().includes(search.toLowerCase())); const value=Number(amount); const promo=promotions.find(p=>p.currency?.toUpperCase()===currency.toUpperCase()); const bonus=promo&&Number.isFinite(value)&&value>=Number(promo.minDeposit||0)?Math.min(value*Number(promo.bonusPercent||0)/100,promo.maxBonus==null?Infinity:Number(promo.maxBonus)):0;
 const submit=async()=>{setError("");if(!method)return setError("Select a payment method.");if(!Number.isFinite(value)||value<=0)return setError("Enter a valid amount.");setPaying(true);try{const r=await fetch("/api/user/transactions/",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({type:"deposit",amount:value,currency,method:method.key,promoCode:promoCode.trim()||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Deposit request failed");if(d.url){window.location.assign(d.url);return}setDone(true)}catch(e:any){setError(e.message)}finally{setPaying(false)}};
 const icon=(t:string)=>t==="card"?<CreditCard/>:t==="crypto"?<Bitcoin/>:t==="bank"?<Landmark/>:<Wallet/>; const copy=async(v:string)=>{try{await navigator.clipboard.writeText(v)}catch{}};
 if(done)return <div className="min-h-screen bg-[#f7f5f1] flex items-center justify-center p-5"><div className="max-w-md w-full bg-white rounded-3xl border border-[#e5e1da] p-8 text-center shadow-sm"><Check className="mx-auto w-16 h-16 text-[#16884a]"/><h1 className="text-2xl font-black mt-4">Funding request received</h1><p className="text-sm text-[#6d6963] mt-2">Your transaction is pending until the configured payment confirmation or authorised review.</p><Link href="/dashboard/" className="inline-flex mt-6 px-5 py-3 rounded-xl bg-[#171717] text-white font-bold">Back to Dashboard</Link></div></div>;
 return <div className="min-h-screen bg-[#f7f5f1] text-[#171717]"><header className="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-[#e5e1da]"><div className="max-w-5xl mx-auto px-4 py-4 flex items-center gap-3"><Link href="/dashboard/" className="p-2 rounded-lg hover:bg-[#f3f0eb]"><ArrowLeft size={19}/></Link><div><p className="text-[10px] uppercase tracking-[.16em] font-bold text-[#817b74]">Funds</p><h1 className="font-black">Add Funds</h1></div><div className="ml-auto flex items-center gap-2 text-xs font-bold text-[#16884a]"><ShieldCheck size={17}/> Secure funding</div></div></header><main className="max-w-5xl mx-auto px-4 py-7 grid lg:grid-cols-[1fr_340px] gap-6"><section className="bg-white rounded-3xl border border-[#e5e1da] shadow-sm overflow-hidden"><div className="px-6 pt-6"><p className="text-xs font-bold text-[#817b74]">STEP {step} OF 4</p><h2 className="text-2xl font-black mt-1">Fund your trading account</h2><div className="mt-5 h-1.5 rounded-full bg-[#eeeae4]"><div className="h-full rounded-full bg-[#c7192d] transition-all" style={{width:`${step*25}%`}}/></div></div><div className="p-6">
 {step===1&&<div><label className="text-xs font-bold uppercase text-[#817b74]">Country / Region</label><div className="relative mt-2"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#817b74]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search country" className="w-full pl-10 pr-3 py-3 rounded-xl border border-[#dcd7d0]"/></div><div className="grid sm:grid-cols-2 gap-2 mt-3 max-h-72 overflow-y-auto">{countryList.map(([c,n])=><button key={c} onClick={()=>chooseCountry(c)} className={`p-3 rounded-xl border text-left ${country===c?"border-[#c7192d] bg-[#fff4f5]":"border-[#e5e1da]"}`}><b className="text-sm">{n}</b><span className="block text-[10px] text-[#817b74]">{c}</span></button>)}</div><button disabled={loading} onClick={()=>setStep(2)} className="mt-5 w-full py-3.5 rounded-xl bg-[#171717] text-white font-bold">Continue <ArrowRight size={16} className="inline"/></button></div>}
 {step===2&&<div><label className="text-xs font-bold uppercase text-[#817b74]">Payment method</label>{loading?<p className="py-8 text-sm text-[#817b74]">Loading available methods…</p>:methods.length===0?<div className="mt-3 p-5 rounded-2xl border border-amber-200 bg-amber-50 text-sm text-amber-900"><AlertTriangle className="inline mr-2" size={17}/>No funding method is enabled for this country/currency. Configure one in Admin → Funding methods.</div>:<div className="grid sm:grid-cols-2 gap-3 mt-3">{methods.map(m=><button key={m.id} onClick={()=>setMethod(m)} className={`p-4 rounded-2xl border text-left ${method?.id===m.id?"border-[#c7192d] bg-[#fff4f5] ring-1 ring-[#c7192d]":"border-[#e5e1da]"}`}><div className="flex items-center gap-3">{icon(m.type)}<div><b>{m.name}</b><p className="text-[11px] text-[#817b74]">{m.type==="crypto"?`${m.asset||"Crypto"}${m.network?` · ${m.network}`:""}`:m.type==="card"?"Card payment":"Secure funding method"}</p></div></div></button>)}</div>}<div className="flex gap-2 mt-5"><button onClick={()=>setStep(1)} className="px-5 py-3 rounded-xl border font-bold">Back</button><button disabled={!method} onClick={()=>setStep(3)} className="flex-1 py-3 rounded-xl bg-[#171717] text-white font-bold disabled:opacity-50">Continue</button></div></div>}
 {step===3&&<div><label className="text-xs font-bold uppercase text-[#817b74]">Amount</label><div className="flex mt-2 rounded-xl border border-[#dcd7d0] overflow-hidden"><input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="flex-1 px-4 py-4 outline-none text-lg font-bold"/><select value={currency} onChange={e=>setCurrency(e.target.value)} className="px-4 bg-[#f7f5f1] font-bold"><option>USD</option><option>EUR</option><option>GBP</option></select></div>{method&&(method.minAmount!==null||method.maxAmount!==null)&&<p className="text-xs text-[#817b74] mt-2">Limits: {method.minAmount??"no minimum"} – {method.maxAmount??"no maximum"} {currency}</p>}{promo&&<div className="mt-5 p-4 rounded-2xl bg-[#fff9ed] border border-[#f0dfb5]"><div className="flex gap-2"><Gift size={17} className="text-[#c7192d]"/><div><b className="text-sm">{promo.name}</b><p className="text-xs text-[#6d6963]">{promo.bonusPercent}% bonus · minimum {promo.minDeposit} {promo.currency}</p></div></div><input value={promoCode} onChange={e=>setPromoCode(e.target.value.toUpperCase())} placeholder="Promo code" className="w-full mt-3 px-3 py-2.5 rounded-lg border"/>{bonus>0&&<p className="text-xs font-bold text-[#16884a] mt-2">Estimated bonus: +{bonus.toFixed(2)} {currency}</p>}</div>}<div className="flex gap-2 mt-5"><button onClick={()=>setStep(2)} className="px-5 py-3 rounded-xl border font-bold">Back</button><button disabled={!Number.isFinite(value)||value<=0} onClick={()=>setStep(4)} className="flex-1 py-3 rounded-xl bg-[#171717] text-white font-bold disabled:opacity-50">Review</button></div></div>}
 {step===4&&<div><p className="text-xs font-bold uppercase text-[#817b74]">Review & pay</p><div className="mt-3 rounded-2xl border divide-y"><div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Country</span><b>{countries[country]}</b></div><div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Method</span><b>{method?.name}</b></div><div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Deposit</span><b>{value.toFixed(2)} {currency}</b></div>{bonus>0&&<div className="p-4 flex justify-between"><span className="text-sm text-[#817b74]">Estimated bonus</span><b className="text-[#16884a]">+{bonus.toFixed(2)} {currency}</b></div>}</div>{method?.type==="crypto"&&method.walletAddress&&<div className="mt-4 p-4 rounded-2xl bg-[#f7f5f1]"><b className="text-xs">Send {method.asset||"crypto"} on {method.network||"configured network"} to</b><div className="flex gap-2 mt-2"><code className="flex-1 break-all text-xs bg-white p-3 rounded-lg border">{method.walletAddress}</code><button onClick={()=>copy(method.walletAddress!)} className="p-3 bg-white border rounded-lg"><Copy size={16}/></button></div>{method.instructions&&<p className="text-xs text-[#6d6963] mt-2">{method.instructions}</p>}</div>}{method?.type==="bank"&&<div className="mt-4 p-4 rounded-2xl bg-[#f7f5f1] text-xs space-y-1">{method.bankName&&<p><b>Bank:</b> {method.bankName}</p>}{method.bankAccountName&&<p><b>Account:</b> {method.bankAccountName}</p>}{method.bankAccount&&<p><b>Number:</b> {method.bankAccount}</p>}{method.bankRouting&&<p><b>Routing:</b> {method.bankRouting}</p>}{method.bankSwift&&<p><b>SWIFT:</b> {method.bankSwift}</p>}{method.instructions&&<p className="pt-2">{method.instructions}</p>}</div>}{method?.type==="card"&&<div className="mt-4 p-4 rounded-2xl bg-[#f7f5f1] text-sm">You will be redirected to the configured Stripe checkout. Your balance changes only after Stripe confirms payment.</div>}{error&&<p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<div className="flex gap-2 mt-5"><button onClick={()=>setStep(3)} className="px-5 py-3 rounded-xl border font-bold">Back</button><button disabled={paying} onClick={submit} className="flex-1 py-3 rounded-xl bg-[#c7192d] text-white font-bold">{paying?"Starting secure payment…":method?.type==="card"?"Pay with card":"Submit funding request"}</button></div></div>}
 </div></section><aside className="space-y-4"><div className="bg-white rounded-3xl border border-[#e5e1da] p-5"><p className="text-xs font-bold uppercase text-[#817b74]">Funding summary</p><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#817b74]">Country</span><b>{countries[country]}</b></div><div className="flex justify-between"><span className="text-[#817b74]">Method</span><b>{method?.name||"Select method"}</b></div><div className="flex justify-between"><span className="text-[#817b74]">Amount</span><b>{Number.isFinite(value)&&value>0?`${value.toFixed(2)} ${currency}`:"—"}</b></div></div></div><div className="p-4 rounded-2xl bg-[#171717] text-white text-xs"><ShieldCheck size={17}/><b className="block mt-2">Secure, server-side funding</b><p className="text-white/60 mt-1">No browser-side balance credits. Payment confirmation or authorised review is required.</p></div></aside></main><LiveChatBot/></div>;
}
