"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CreditCard, Bitcoin, Landmark, Wallet, Plus, Save, Trash2, RefreshCw } from "lucide-react";
import { getAuthToken } from "@/lib/client-auth";

type Method = any;
const empty = { key:"",name:"",type:"crypto",enabled:false,countries:"",currencies:"USD",minAmount:"",maxAmount:"",instructions:"",asset:"",network:"",walletAddress:"",bankName:"",bankAccountName:"",bankAccount:"",bankRouting:"",bankSwift:"",stripeEnabled:false,stripePublicKey:"",logoUrl:"",sortOrder:"0" };

export default function AdminFundingPage(){
 const [methods,setMethods]=useState<Method[]>([]),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
 const api=async(path:string,options:RequestInit={})=>{const token=getAuthToken();if(!token)throw new Error("Admin authentication required");const r=await fetch(path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;};
 const load=async()=>{setLoading(true);try{const d=await api("/api/admin/funding-methods/");setMethods(d.methods||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async()=>{setSaving(true);setError("");try{const body={...form,minAmount:form.minAmount===""?null:Number(form.minAmount),maxAmount:form.maxAmount===""?null:Number(form.maxAmount),sortOrder:Number(form.sortOrder||0)};if(editing)await api("/api/admin/funding-methods/",{method:"PATCH",body:JSON.stringify({id:editing,...body})});else await api("/api/admin/funding-methods/",{method:"POST",body:JSON.stringify(body)});setForm(empty);setEditing(null);await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 const edit=(m:any)=>{setEditing(m.id);setForm({...m,minAmount:m.minAmount??"",maxAmount:m.maxAmount??"",sortOrder:String(m.sortOrder??0)})};
 const remove=async(id:string)=>{if(!confirm("Delete this funding method?"))return;try{await api(`/api/admin/funding-methods/?id=${encodeURIComponent(id)}`,{method:"DELETE"});await load()}catch(e:any){setError(e.message)}};
 const icon=(type:string)=>type==="card"?<CreditCard size={19}/>:type==="crypto"?<Bitcoin size={19}/>:type==="bank"?<Landmark size={19}/>:<Wallet size={19}/>;
 const field=(key:string,label:string,wide=false)=><input value={form[key]??""} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label} className={`${wide?"sm:col-span-2":""} w-full px-3 py-3 rounded-xl border border-[#ddd8d1] bg-white text-sm`}/>;
 return <div className="min-h-screen bg-[#f7f5f1] text-[#171717]"><header className="sticky top-0 z-50 bg-white border-b border-[#e5e1da] px-4 py-4"><div className="max-w-5xl mx-auto flex items-center gap-3"><Link href="/admin/" className="p-2 rounded-lg hover:bg-[#f3f0eb]"><ArrowLeft size={19}/></Link><div><p className="text-[10px] uppercase tracking-widest text-[#817b74] font-bold">Administration</p><h1 className="font-black">Funding methods</h1></div><button onClick={load} className="ml-auto p-2 rounded-lg hover:bg-[#f3f0eb]"><RefreshCw size={17} className={loading?"animate-spin":""}/></button></div></header>
 <main className="max-w-5xl mx-auto p-4 py-7 space-y-5">{error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm font-semibold">{error}</div>}
 <section className="bg-white rounded-3xl border border-[#e5e1da] p-5"><div className="flex items-center gap-2 mb-4"><Plus size={19}/><h2 className="font-black">{editing?"Edit funding method":"Add funding method"}</h2></div><div className="grid sm:grid-cols-2 gap-3">{field("key","Unique key (e.g. skrill)")}{field("name","Display name (e.g. Skrill)")}{field("logoUrl","Brand logo URL (optional)")}{field("currencies","Currencies, comma separated (USD,EUR)")}{field("countries","Country codes, comma separated (US,GB). Blank = GLOBAL")}{field("minAmount","Minimum amount")}{field("maxAmount","Maximum amount")}{field("sortOrder","Display order")}{form.type==="crypto"&&<>{field("asset","Crypto asset (e.g. USDT)")}{field("network","Network (e.g. TRC20)")}{field("walletAddress","Wallet address",true)}</>}{form.type==="bank"&&<>{field("bankName","Bank name")}{field("bankAccountName","Account name")}{field("bankAccount","Account number")}{field("bankRouting","Routing number")}{field("bankSwift","SWIFT / BIC")}</>}{form.type==="card"&&field("stripePublicKey","Stripe publishable key")}{field("instructions","Customer instructions",true)}<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="px-3 py-3 rounded-xl border border-[#ddd8d1] text-sm"><option value="card">Card</option><option value="crypto">Crypto</option><option value="bank">Bank transfer</option><option value="wallet">Wallet / e-wallet</option><option value="other">Other</option></select></div><div className="flex flex-wrap gap-5 mt-4 text-xs font-bold"><label><input type="checkbox" checked={!!form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enable for customers</label>{form.type==="card"&&<label><input type="checkbox" checked={!!form.stripeEnabled} onChange={e=>setForm({...form,stripeEnabled:e.target.checked})}/> Stripe enabled</label>}</div><div className="flex gap-2 mt-5"><button onClick={()=>{setForm(empty);setEditing(null)}} className="px-5 py-3 rounded-xl border font-bold text-sm">Clear</button><button disabled={saving} onClick={save} className="flex-1 py-3 rounded-xl bg-[#c7192d] text-white font-bold text-sm"><Save size={15} className="inline mr-2"/>{saving?"Saving…":editing?"Save changes":"Create method"}</button></div></section>
 <section className="space-y-3"><h2 className="font-black">Configured methods</h2>{methods.length===0&&!loading&&<div className="bg-white p-5 rounded-2xl border border-amber-200 text-sm">No funding methods configured yet.</div>}{methods.map(m=><div key={m.id} className="bg-white rounded-2xl border border-[#e5e1da] p-4"><div className="flex gap-3 items-start"><div className="w-10 h-10 rounded-xl bg-[#f7f5f1] flex items-center justify-center overflow-hidden">{m.logoUrl?<img src={m.logoUrl} alt="" className="w-7 h-7 object-contain"/>:icon(m.type)}</div><div className="flex-1 min-w-0"><div className="flex justify-between gap-3"><div><p className="font-black">{m.name}</p><p className="text-[11px] text-[#817b74]">{m.key} · {m.type} · {m.countries?.trim()?m.countries:"GLOBAL"} · {m.currencies||"all currencies"}</p></div><span className={`px-2 py-1 rounded-full text-[10px] font-bold ${m.enabled?"bg-green-100 text-green-700":"bg-[#f1eee9] text-[#817b74]"}`}>{m.enabled?"Enabled":"Disabled"}</span></div>{m.type==="crypto"&&<p className="text-xs mt-2 break-all">{m.asset||"Crypto"} · {m.network||"Network not set"} · {m.walletAddress||"Wallet address not set"}</p>}{m.type==="card"&&<p className="text-xs mt-2">Stripe: {m.stripeEnabled?"enabled":"disabled"}</p>}</div><div className="flex gap-1"><button onClick={()=>edit(m)} className="px-3 py-2 rounded-lg bg-[#f3f0eb] text-xs font-bold">Edit</button><button onClick={()=>remove(m.id)} className="p-2 rounded-lg bg-red-50 text-red-700" aria-label="Delete"><Trash2 size={15}/></button></div></div></div>)}</section>
 </main></div>;
}
